version: '2'
services:
  moodle:
    image: docker.io/bitnami/moodle:latest
    ports:
      - 80:8080
      - 443:8443
    environment:
      - MOODLE_DATABASE_HOST=172.31.31.167
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - /var/www/html/moodle:/bitnami/moodle
      - /var/www/html/moodledata:/bitnami/moodledata